# Generated by Django 3.1 on 2022-05-07 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=uuid.uuid1, max_length=300, unique=True)),
                ('priority', models.IntegerField(default=uuid.uuid1)),
                ('description', models.TextField(default='')),
                ('image', models.CharField(default='', max_length=200)),
                ('link', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
