# Generated by Django 3.1 on 2022-05-11 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projects_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=uuid.uuid1, max_length=300, unique=True)),
                ('description', models.TextField(default='')),
                ('image_link', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anish Chapagai', max_length=100)),
                ('image_link', models.TextField(default='')),
            ],
        ),
    ]
