# Generated by Django 3.1 on 2022-05-20 12:53

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_me_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='music',
            field=models.FileField(default='', upload_to=portfolio.models.Me.get_available_name),
        ),
    ]
