# Generated by Django 4.0.4 on 2022-05-24 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=uuid.uuid1, max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewReleases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=uuid.uuid1, max_length=300, unique=True)),
                ('last_ep', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=uuid.uuid1, max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=uuid.uuid1, max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=uuid.uuid1, max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=uuid.uuid1, max_length=30, unique=True)),
                ('image_link', models.CharField(default='#', max_length=200)),
                ('url', models.CharField(default='#', max_length=200)),
                ('summary', models.TextField(default='')),
                ('genre', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='', max_length=20)),
                ('episodes', models.IntegerField(default=1)),
                ('released', models.IntegerField(default=1)),
            ],
        ),
    ]
