# Generated by Django 3.1 on 2022-05-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aniwatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Top',
            new_name='Popular',
        ),
    ]
