# Generated by Django 3.1 on 2022-04-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniwatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recents',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='recommended',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='trending',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
