# Generated by Django 4.0.4 on 2022-05-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniwatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='anime_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
