# Generated by Django 4.0.4 on 2022-06-02 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aniwatch', '0002_video_anime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='anime_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default=uuid.uuid1, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
